/**
 * Provider-agnostic storage interface. `upload`/`delete`/`read` are all a
 * caller needs regardless of backend — access control is handled entirely
 * at the app layer (app/api/photos/[id]/route.ts), never by the provider or
 * by a public URL, so no provider needs to expose a `getUrl()`. Swapping
 * `filesystem-provider.ts` for an S3-backed one later means implementing
 * this same interface and switching `STORAGE_PROVIDER` — nothing else in
 * the app (actions, DAL, components) references a provider directly.
 */
export interface StorageProvider {
  /** Stores bytes under `key` (already generated by `generateStorageKey`). */
  upload(key: string, buffer: Buffer): Promise<void>;
  /** Reads back the stored bytes for `key`. Throws if the key doesn't exist. */
  read(key: string): Promise<Buffer>;
  /** Removes a stored object. Safe to call on an already-missing key. */
  delete(key: string): Promise<void>;
}
